openapi: '3.0.0'
info:
  title: 'QNX Team Blockchain Capstone Project'
  version: '1.0.0'
  description: >-
    Blockchain Capstone Project by Team QNX.

paths:
  "/api/health":
    get:
      tags:
      - Monitor Health

      operationId: monitorHealth
      summary: Get health status of app
      description: Get health status of app
      responses:
        default:
          description: Health check response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Server is up!"

  "/api/user/add":
    post:
      summary: Create new user
      tags:
      - User Enrollment
      description: Register user
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/definitions/userAddFarmerSource"
                - $ref: "#/definitions/userAddWholesalerSource"
            examples:
              farmer:
                $ref: "#/components/examples/userAddFarmerSource"
              wholesaler:
                $ref: "#/components/examples/userAddWholesalerSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "User enrolled successfully"
                    
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"

  "/api/token":
    post:
      summary: Create access token 
      tags:
      - Access Token
      description: Get access token
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/accessTokenSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
  
definitions:
  userAddFarmerSource:
    properties: 
      username:
        type: string
        example: "username"
      password:
        type: string
        example: "password"
      userId:
        type: string
        example: "1"
      role:
        type: string
        example: "farmer"
      firstName:
        type: string
        example: "Jodie"
      lastName:
        type: string
        example: "Cristobal"
      addressLine:
        type: string
        example: "037 R. Higgins St., Brgy 185"
      city:
        type: string
        example: "La Trinidad"
      province:
        type: string
        example: "Benguet"
      zipcode:
        type: string
        example: "1300"
      latlong:
        type: string
        example: "14.543610, 120.994453"
      farmerType:
        type: string
        example: "livestock/crop/aquaculture/horticulture"
      mainGoods:
        type: string
        example: "dairy/poultry/meat/hide/flower/shrub/sod/fish/shellfish/grain/fiber/fruit/vegetable"
      mobile:
        type: string
        example: "09123456789"
      farmerDesc:
        type: string
        example: "Farmer from La Trinidad, Benguet. Farms Bahay Kubo vegetables. Don\u0027t worry it\u0027s organic" 
  userAddWholesalerSource:
    properties: 
      username:
        type: string
        example: "username"
      password:
        type: string
        example: "password"
      userId:
        type: string
        example: "1"
      role:
        type: string
        example: "wholesaler"
      firstName:
        type: string
        example: "Jodie"
      lastName:
        type: string
        example: "Cristobal"
      storeName:
        type: string
        example: "Cristobal Store"
      addressLine:
        type: string
        example: "037 R. Higgins St., Brgy 185"
      city:
        type: string
        example: "La Trinidad"
      province:
        type: string
        example: "Benguet"
      zipcode:
        type: string
        example: "1300"
      latlong:
        type: string
        example: "14.543610, 120.994453"
      mobile:
        type: string
        example: "09123456789"
      wholesalerDesc:
        type: string
        example: "Interested in procuring vegetables for processing"  

  accessTokenSource:
    properties:
        username:
          type: string
          example: "username"
        password:
          type: string
          example: "password"

  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        example: false
      message:
        type: string
        example: "Error message"
              
components:
  examples:
    userAddFarmerSource:
      summary: farmer
      value: 
        username: "username"
        password: "password"
        userId: "1"
        role: "farmer"
        firstName: "Jodie"
        lastName: "Cristobal"
        addressLine: "037 R. Higgins St., Brgy 185"
        city: "La Trinidad"
        province: "Benguet"
        zipcode: "1300"
        latlong: "14.543610, 120.994453"
        farmerType: "livestock/crop/aquaculture/horticulture"
        mainGoods: "dairy/poultry/meat/hide/flower/shrub/sod/fish/shellfish/grain/fiber/fruit/vegetable"
        mobile: "09123456789"
        farmerDesc: "Farmer from La Trinidad, Benguet. Farms Bahay Kubo vegetables. Don\u0027t worry it\u0027s organic" 
    userAddWholesalerSource:
      summary: wholesaler
      value: 
        username: "username"
        password: "password"
        userId: "1"
        role: "wholesaler"
        firstName: "Jodie"
        lastName: "Cristobal"
        storeName: "Cristobal Store"
        addressLine: "037 R. Higgins St., Brgy 185"
        city: "La Trinidad"
        province: "Benguet"
        zipcode: "1300"
        latlong: "14.543610, 120.994453"
        mobile: "09123456789"
        wholesalerDesc: "Interested in procuring vegetables for processing"  

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
